version = 0.1
[dev.deploy.parameters]
stack_name = "song-share-dev"
resolve_s3 = true
s3_prefix = "song-share-dev"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
